networks:
  subscriptions-service-net:
    driver: bridge

services:
  subscriptions-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: subscriptions-service
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      subscriptions-service-net:

  postgres:
    image: postgres:17.5
    container_name: postgresClient
    env_file:
      - config/config.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - subscriptions-service-net