CREATE SCHEMA IF NOT EXISTS schema_subscriptions;

CREATE TABLE IF NOT EXISTS schema_subscriptions.subscriptions
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name TEXT,
    price INT NOT NULL,
    user_id TEXT,
    start_date TEXT NOT NULL,
    end_date TEXT
);